apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1  # MySQL은 기본적으로 1개의 인스턴스로 실행
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0 # MySQL 5.7 이미지 사용
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "petclinic"
            - name: MYSQL_USER
              value: "petclinic"
            - name: MYSQL_PASSWORD
              value: "petclinic"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306      # 외부에서 접근할 포트
      targetPort: 3306 # MySQL 컨테이너 내부 포트
  clusterIP: None     # MySQL 서비스에 대한 고정 IP 할당, 클러스터 내부 DNS 이름 사용

